version: 0.2

phases:
  install:
    commands:
     # variables
      - echo $CODEBUILD_SRC_DIR
      #- ls build/libs
      #- stat src-0.0.1-SNAPSHOT.jar
      #- stat build/libs/src-0.0.1-SNAPSHOT.jar
      - ls
      - REPOSITORY_URI=016973021151.dkr.ecr.us-west-1.amazonaws.com/ecs-example-repository
      - ARTIFACT=spring-boot
      - ARTIFACT_TYPE=.jar 
      - TAG_NAME=$REPOSITORY_URI:$ARTIFACT
      - echo $AWS_DEFAULT_REGION 
      - echo $ARTIFACT
      - echo $ARTIFACT_TYPE
      - echo $REPOSITORY_URI
      - echo $TAG_NAME  
    
  pre_build:
    commands:

  build:
    commands:      
      - echo Building the Docker image...  
      - docker build -f src/main/docker/Dockerfile -t $TAG_NAME .
      - docker tag $TAG_NAME $TAG_NAME
  post_build:
    commands:
       - $(aws ecr get-login --region eu-west-3 --no-include-email) 
       - echo Build completed on `date`
       - echo Pushing the Docker images...
       - docker push $TAG_NAME
       #- aws ecs list-services --cluster UngerwECS
       #- aws ecs update-service --cluster UngerwECS --service UngerwServiceComplete-Service-1I21NO0BAHCJY --task-definition spring-boot
       
#artifacts:
#     files:  target/spring-boot.jar